export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";
export const POST_DETAILS_RESET = "POST_DETAILS_RESET";

export const POST_CREATE_COMMENT_REQUEST = "POST_CREATE_COMMENT_REQUEST";
export const POST_CREATE_COMMENT_SUCCESS = "POST_CREATE_COMMENT_SUCCESS";
export const POST_CREATE_COMMENT_FAIL    = "POST_CREATE_COMMENT_FAIL";
export const POST_CREATE_COMMENT_RESET   = "POST_CREATE_COMMENT_RESET";

export const POST_LIST_COMMENTS_REQUEST = "POST_LIST_COMMENTS_REQUEST";
export const POST_LIST_COMMENTS_SUCCESS = "POST_LIST_COMMENTS_SUCCESS";
export const POST_LIST_COMMENTS_FAIL    = "POST_LIST_COMMENTS_FAIL";
export const POST_LIST_COMMENTS_RESET   = "POST_LIST_COMMENTS_RESET";

export const POST_CREATE_LIKE_REQUEST = "POST_CREATE_LIKE_REQUEST";
export const POST_CREATE_LIKE_SUCCESS = "POST_CREATE_LIKE_SUCCESS";
export const POST_CREATE_LIKE_FAIL = "POST_CREATE_LIKE_FAIL";
export const POST_CREATE_LIKE_RESET = "POST_CREATE_LIKE_RESET";

export const POST_TRENDING_REQUEST = "POST_TRENDING_REQUEST";
export const POST_TRENDING_SUCCESS = "POST_TRENDING_SUCCESS";
export const POST_TRENDING_FAIL = "POST_TRENDING_FAIL";


export const POST_COMMENT_DELETE_REQUEST = "POST_COMMENT_DELETE_REQUEST";
export const POST_COMMENT_DELETE_SUCCESS = "POST_COMMENT_DELETE_SUCCESS";
export const POST_COMMENT_DELETE_FAIL = "POST_COMMENT_DELETE_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";
export const POST_UPDATE_RESET = "POST_UPDATE_RESET";

export const POST_LIST_MY_REQUEST = "POST_LIST_MY_REQUEST";
export const POST_LIST_MY_SUCCESS = "POST_LIST_MY_SUCCESS";
export const POST_LIST_MY_FAIL = "POST_LIST_MY_FAIL";
export const POST_LIST_MY_RESET = "POST_LIST_MY_RESET";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
export const CATEGORY_LIST_RESET = "CATEGORY_LIST_RESET";

export const CATEGORY_CREATE_REQUEST = "CATEGORY_CREATE_REQUEST";
export const CATEGORY_CREATE_SUCCESS = "CATEGORY_CREATE_SUCCESS";
export const CATEGORY_CREATE_FAIL    = "CATEGORY_CREATE_FAIL";
export const CATEGORY_CREATE_RESET   = "CATEGORY_CREATE_RESET";

export const CATEGORY_DETAILS_REQUEST = "CATEGORY_DETAILS_REQUEST";
export const CATEGORY_DETAILS_SUCCESS = "CATEGORY_DETAILS_SUCCESS";
export const CATEGORY_DETAILS_FAIL    = "CATEGORY_DETAILS_FAIL";
export const CATEGORY_DETAILS_RESET   = "CATEGORY_DETAILS_RESET";

export const CATEGORY_UPDATE_REQUEST = "CATEGORY_UPDATE_REQUEST";
export const CATEGORY_UPDATE_SUCCESS = "CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAIL    = "CATEGORY_UPDATE_FAIL";
export const CATEGORY_UPDATE_RESET   = "CATEGORY_UPDATE_RESET";

export const CATEGORY_DELETE_REQUEST = "CATEGORY_DELETE_REQUEST";
export const CATEGORY_DELETE_SUCCESS = "CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAIL    = "CATEGORY_DELETE_FAIL";